import 'package:flutter/material.dart';
import 'package:covid19_app/models/generatedvaccinedshot2widget/generated/GeneratedBottombarWidget5.dart';
import 'package:covid19_app/models/generatedvaccinedshot2widget/generated/GeneratedGroup3Widget4.dart';
import 'package:covid19_app/models/generatedvaccinedshot2widget/generated/Generated1280pxEo_circle_green_white_checkmark1Widget.dart';
import 'package:covid19_app/models/generatedvaccinedshot2widget/generated/GeneratedCERTIFICATEFOR02PERVACCINATIONWidget.dart';
import 'package:covid19_app/models/generatedvaccinedshot2widget/generated/GeneratedNavBarWidget6.dart';
import 'package:covid19_app/models/generatedvaccinedshot2widget/generated/GeneratedRectangle5Widget2.dart';
import 'package:covid19_app/models/generatedvaccinedshot2widget/generated/GeneratedGroup2Widget2.dart';
import 'package:covid19_app/models/generatedvaccinedshot2widget/generated/Generated1280pxEo_circle_green_white_number21Widget.dart';

/* Frame Vaccined shot 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVaccinedshot2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 375.0,
              height: 812.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 255, 255, 255),
                      ),
                    ),
                    Positioned(
                      left: 21.0,
                      top: 109.0,
                      right: null,
                      bottom: null,
                      width: 336.0,
                      height: 589.0,
                      child: GeneratedRectangle5Widget2(),
                    ),
                    Positioned(
                      left: 36.0,
                      top: 577.0,
                      right: null,
                      bottom: null,
                      width: 305.0,
                      height: 106.0,
                      child: GeneratedGroup3Widget4(),
                    ),
                    Positioned(
                      left: 36.0,
                      top: 450.0,
                      right: null,
                      bottom: null,
                      width: 305.0,
                      height: 106.0,
                      child: GeneratedGroup2Widget2(),
                    ),
                    Positioned(
                      left: 42.0,
                      top: 300.0,
                      right: null,
                      bottom: null,
                      width: 295.0,
                      height: 66.0,
                      child: GeneratedCERTIFICATEFOR02PERVACCINATIONWidget(),
                    ),
                    Positioned(
                      left: 51.0,
                      top: 598.0,
                      right: null,
                      bottom: null,
                      width: 70.0,
                      height: 70.0,
                      child:
                          Generated1280pxEo_circle_green_white_number21Widget(),
                    ),
                    Positioned(
                      left: 144.0,
                      top: 178.0,
                      right: null,
                      bottom: null,
                      width: 90.0,
                      height: 90.0,
                      child:
                          Generated1280pxEo_circle_green_white_checkmark1Widget(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: null,
                      bottom: null,
                      width: 375.0,
                      height: 90.0,
                      child: GeneratedNavBarWidget6(),
                    )
                  ]),
            ),
            Positioned(
              left: 0.0,
              top: 683.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 129.0,
              child: GeneratedBottombarWidget5(),
            )
          ]),
    ));
  }
}
