import 'package:flutter/material.dart';
import 'package:covid19_app/models/generatedvaccinedshot0widget/generated/GeneratedRectangle5Widget.dart';
import 'package:covid19_app/models/generatedvaccinedshot0widget/generated/GeneratedFOR0PERVACCINATIONWidget.dart';
import 'package:covid19_app/models/generatedvaccinedshot0widget/generated/GeneratedErroricon252431Widget.dart';
import 'package:covid19_app/models/generatedvaccinedshot0widget/generated/GeneratedBottombarWidget1.dart';
import 'package:covid19_app/models/generatedvaccinedshot0widget/generated/GeneratedGroup3Widget.dart';
import 'package:covid19_app/models/generatedvaccinedshot0widget/generated/GeneratedNavBarWidget2.dart';

/* Frame Vaccined shot 0
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVaccinedshot0Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              return SingleChildScrollView(
                scrollDirection: Axis.horizontal,
                child: Container(
                    width: 376.0,
                    child: Stack(children: [
                      Container(
                          height: constraints.maxHeight,
                          child: Container(
                            width: 375.0,
                            height: 812.0,
                            child: Stack(
                                fit: StackFit.expand,
                                alignment: Alignment.center,
                                overflow: Overflow.visible,
                                children: [
                                  ClipRRect(
                                    borderRadius: BorderRadius.zero,
                                    child: Container(
                                      color: Color.fromARGB(255, 255, 255, 255),
                                    ),
                                  ),
                                  Positioned(
                                    left: 21.0,
                                    top: 117.0,
                                    right: null,
                                    bottom: null,
                                    width: 336.0,
                                    height: 585.0,
                                    child: GeneratedRectangle5Widget(),
                                  ),
                                  Positioned(
                                    left: 52.0,
                                    top: 599.0,
                                    right: null,
                                    bottom: null,
                                    width: 272.0,
                                    height: 70.0,
                                    child: GeneratedGroup3Widget(),
                                  ),
                                  Positioned(
                                    left: 48.0,
                                    top: 300.0,
                                    right: null,
                                    bottom: null,
                                    width: 282.0,
                                    height: 30.0,
                                    child: GeneratedFOR0PERVACCINATIONWidget(),
                                  ),
                                  Positioned(
                                    left: 144.0,
                                    top: 178.0,
                                    right: null,
                                    bottom: null,
                                    width: 90.0,
                                    height: 90.0,
                                    child: GeneratedErroricon252431Widget(),
                                  ),
                                  Positioned(
                                    left: 1.0,
                                    top: 0.0,
                                    right: null,
                                    bottom: null,
                                    width: 375.0,
                                    height: 90.0,
                                    child: GeneratedNavBarWidget2(),
                                  )
                                ]),
                          ))
                    ])),
              );
            }),
            Positioned(
              left: 0.0,
              top: 683.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 129.0,
              child: GeneratedBottombarWidget1(),
            )
          ]),
    ));
  }
}
